package com.iridium.xskullstest.utils;

import java.util.Arrays;
import java.util.List;

public class Usernames {
    public static List<String> usernames = Arrays.asList(
            "yourmom1212",
            "ybe",
            "Scavage",
            "Tinchosz",
            "daerb",
            "verflow",
            "Brazzer",
            "Trillest",
            "EZix",
            "Meritocracia",
            "otpe",
            "nn_mc",
            "Hershey",
            "ElsaPlayzz",
            "HACKIN0706",
            "Angelisim",
            "iFraz",
            "KolevBG",
            "thebreadrat",
            "VIRGlN",
            "ImPuddles",
            "AlphaAce",
            "ggsophie",
            "TheDark_00",
            "yeezydealer",
            "HKa1",
            "Natheyy",
            "l0ves1ckk",
            "Bucyrus",
            "lunyi",
            "AusJM",
            "axl_guilherme",
            "rageqt",
            "SkyKazukamx",
            "CaptureTheFag",
            "amanloe73",
            "TomZLord",
            "Lucetie",
            "ShwMendes",
            "DossinJ",
            "giahuy12",
            "Tue12",
            "golden_labrador",
            "Fortnite_lover69",
            "xytc",
            "Hotys",
            "hrparkour",
            "ImM7mDx_",
            "CheddaCheese",
            "zvowasthere",
            "n4rc1s5us",
            "adorablepug9",
            "Availia",
            "Havok_dsc",
            "RizzOLX",
            "orow",
            "Shondell",
            "Affixial",
            "araneaus"
    );
}
