package com.iridium.xskullstest.utils;

import java.util.Arrays;
import java.util.List;

public class Usernames {
    public static List<String> usernames = Arrays.asList(
            "xSkyward",
            "Ksawery2212",
            "Sigma_Czarny",
            "NOTTNOVACRAFT",
            "Esmia",
            "MetalFreezer",
            "LegitSpeedMine",
            "Lxvelesslair",
            "chadwickjr_",
            "senachya",
            "PrincessHeinz",
            "hobbang_S2",
            "PRFUM",
            "Reshael_Fatui",
            "dylanrivero",
            "Only_Arkh",
            "HazardGibMeAdmin",
            "ccyber1",
            "GERMANALTACCOUNT",
            "xDerScammer",
            "Zj3rany_69",
            "Yoossef",
            "ArklingorFlazer_",
            "xBerghuis_",
            "Incomprehendable",
            "lea_1323",
            "FriedPickleBoy",
            "Pewbie",
            "DaddyAxo",
            "KarmaLegends",
            "Haruki_Natsu",
            "WizardandJedi",
            "kikizinhaa",
            "ASFF_",
            "Chihrovo",
            "MrBubblees",
            "KRUTOIREPER",
            "WaywardRen",
            "Sploopex",
            "Zarkenn",
            "Preauthorization",
            "IeshaIsBack",
            "tiger8093028",
            "_White_crow_7",
            "SoyDeLuciana",
            "fuvn",
            "grapecorn",
            "miRTaka_10",
            "gekkie",
            "Gl4cies_",
            "STAWIKFN",
            "Inesperavel",
            "mircuzzo25",
            "Xackstar",
            "Odklejonyyy_",
            "VolkovWolf",
            "stel0k",
            "Huniboaa",
            "AnhHao"
    );
}
